<input type="hidden" name="id" value="<?php echo $_POST['id'];?>">
<input type="hidden" name="listings_id" value="<?php echo $_POST['listings_id'];?>">
<input type="hidden" name="members_id" value="<?php echo $_POST['members_id'];?>">
<input type="hidden" name="name" value="<?php echo $_POST['name'];?>">
<input type="hidden" name="email" value="<?php echo $_POST['email'];?>">
<input type="hidden" name="phone" value="<?php echo $_POST['phone'];?>">
<input type="hidden" name="good_point" value="<?php echo implode(",",$_POST['good_point']);?>">
<input type="hidden" name="contact_type" value="<?php echo $_POST['contact_type'];?>">
<input type="hidden" name="nationality" value="<?php echo $_POST['nationality'];?>">
<input type="hidden" name="created" value="<?php echo $_POST['created'];?>">
