<input type="hidden" name="id" value="<?php echo $_POST['id'];?>">
<input type="hidden" name="companies_id" value="<?php echo $_POST['companies_id'];?>">
<input type="hidden" name="email" value="<?php echo $_POST['email'];?>">
<input type="hidden" name="password" value="<?php echo $_POST['password'];?>">
<input type="hidden" name="password2" value="<?php echo $_POST['password2'];?>">
<input type="hidden" name="title" value="<?php echo $_POST['title'];?>">
<input type="hidden" name="first_name" value="<?php echo $_POST['first_name'];?>">
<input type="hidden" name="last_name" value="<?php echo $_POST['last_name'];?>">
<input type="hidden" name="position" value="<?php echo $_POST['position'];?>">
<input type="hidden" name="tel" value="<?php echo $_POST['tel'];?>">
<input type="hidden" name="mobile" value="<?php echo $_POST['mobile'];?>">
<input type="hidden" name="published_range_of_inquiry" value="<?php echo implode(",",$_POST['published_range_of_inquiry']);?>">
