<input type="hidden" name="id" value="<?php echo $_POST['id'];?>">
<input type="hidden" name="evernote_id" value="<?php echo $_POST['evernote_id'];?>">
<input type="hidden" name="name" value="<?php echo $_POST['name'];?>">
<input type="hidden" name="code" value="<?php echo $_POST['code'];?>">
<input type="hidden" name="companies_id" value="<?php echo $_POST['companies_id'];?>">
<input type="hidden" name="developer_id" value="<?php echo $_POST['developer_id'];?>">
<input type="hidden" name="billing_id" value="<?php echo $_POST['billing_id'];?>">
<input type="hidden" name="states_id" value="<?php echo $_POST['states_id'];?>">
<input type="hidden" name="groups_id" value="<?php echo $_POST['groups_id'];?>">
<input type="hidden" name="locations_id" value="<?php echo $_POST['locations_id'];?>">
<input type="hidden" name="property_types_id" value="<?php echo implode(",",$_POST['property_types_id']);?>">
<input type="hidden" name="property_name" value="<?php echo $_POST['property_name'];?>">
<input type="hidden" name="prices_id" value="<?php echo implode(",",$_POST['prices_id']);?>">
<input type="hidden" name="price_name" value="<?php echo $_POST['price_name'];?>">
<input type="hidden" name="price_minimum" value="<?php echo $_POST['price_minimum'];?>">
<input type="hidden" name="price_minimum_per_sqft" value="<?php echo $_POST['price_minimum_per_sqft'];?>">
<input type="hidden" name="features_id" value="<?php echo implode(",",$_POST['features_id']);?>">
<input type="hidden" name="catch_copy" value="<?php echo $_POST['catch_copy'];?>">
<input type="hidden" name="image_path" value="<?php echo $_POST['image_path'];?>">
<input type="hidden" name="main_picture" value="<?php echo $_POST['main_picture'];?>">
<input type="hidden" name="address" value="<?php echo $_POST['address'];?>">
<input type="hidden" name="latitude" value="<?php echo $_POST['latitude'];?>">
<input type="hidden" name="longitude" value="<?php echo $_POST['longitude'];?>">
<input type="hidden" name="completion_years_id" value="<?php echo implode(",",$_POST['completion_years_id']);?>">
<input type="hidden" name="completion_year" value="<?php echo $_POST['completion_year'];?>">
<input type="hidden" name="bedrooms_id" value="<?php echo implode(",",$_POST['bedrooms_id']);?>">
<input type="hidden" name="sizes_id" value="<?php echo implode(",",$_POST['sizes_id']);?>">
<input type="hidden" name="tenures_id" value="<?php echo $_POST['tenures_id'];?>">
<input type="hidden" name="sales_garellies_id" value="<?php echo implode(",",$_POST['sales_garellies_id']);?>">
<input type="hidden" name="youtube_url" value="<?php echo $_POST['youtube_url'];?>">
<input type="hidden" name="type" value="<?php echo $_POST['type'];?>">
<input type="hidden" name="search_rank" value="<?php echo $_POST['search_rank'];?>">
<input type="hidden" name="status" value="<?php echo $_POST['status'];?>">
<input type="hidden" name="posted_date" value="<?php echo $_POST['posted_date'];?>">
<input type="hidden" name="expiry_date" value="<?php echo $_POST['expiry_date'];?>">
<input type="hidden" name="launch_date" value="<?php echo $_POST['launch_date'];?>">
<input type="hidden" name="monthly_enquiry_limit" value="<?php echo $_POST['monthly_enquiry_limit'];?>">
<input type="hidden" name="service_fee" value="<?php echo $_POST['service_fee'];?>">
<input type="hidden" name="call_option" value="<?php echo $_POST['call_option'];?>">
<input type="hidden" name="contact_no" value="<?php echo $_POST['contact_no'];?>">
<input type="hidden" name="charge_type" value="<?php echo $_POST['charge_type'];?>">
<input type="hidden" name="fixed_fee" value="<?php echo $_POST['fixed_fee'];?>">
<input type="hidden" name="call_option_fee" value="<?php echo $_POST['call_option_fee'];?>">
