<input type="hidden" name="id" value="<?php echo $_POST['id'];?>">
<input type="hidden" name="parent_id" value="<?php echo $_POST['parent_id'];?>">
<input type="hidden" name="name" value="<?php echo $_POST['name'];?>">
<input type="hidden" name="code" value="<?php echo $_POST['code'];?>">
<input type="hidden" name="rank" value="<?php echo $_POST['rank'];?>">
<input type="hidden" name="class" value="<?php echo implode(",",$_POST['class']);?>">
<input type="hidden" name="url" value="<?php echo $_POST['url'];?>">
<input type="hidden" name="address" value="<?php echo $_POST['address'];?>">
<input type="hidden" name="tel" value="<?php echo $_POST['tel'];?>">
<input type="hidden" name="fax" value="<?php echo $_POST['fax'];?>">
<input type="hidden" name="pickup_flag" value="<?php echo $_POST['pickup_flag'];?>">
<input type="hidden" name="developers_list_display_flag" value="<?php echo $_POST['developers_list_display_flag'];?>">
<input type="hidden" name="logo_image_path" value="<?php echo $_POST['logo_image_path'];?>">
<input type="hidden" name="middle_head_1" value="<?php echo $_POST['middle_head_1'];?>">
<input type="hidden" name="desc_image_path_1" value="<?php echo $_POST['desc_image_path_1'];?>">
<input type="hidden" name="body_1" value="<?php echo $_POST['body_1'];?>">
<input type="hidden" name="middle_head_2" value="<?php echo $_POST['middle_head_2'];?>">
<input type="hidden" name="desc_image_path_2" value="<?php echo $_POST['desc_image_path_2'];?>">
<input type="hidden" name="body_2" value="<?php echo $_POST['body_2'];?>">
<input type="hidden" name="middle_head_3" value="<?php echo $_POST['middle_head_3'];?>">
<input type="hidden" name="desc_image_path_3" value="<?php echo $_POST['desc_image_path_3'];?>">
<input type="hidden" name="body_3" value="<?php echo $_POST['body_3'];?>">
