<input type="hidden" name="id" value="<?php echo $_POST['id'];?>">
<input type="hidden" name="listings_id" value="<?php echo $_POST['listings_id'];?>">
<input type="hidden" name="name" value="<?php echo $_POST['name'];?>">
<input type="hidden" name="image_path" value="<?php echo $_POST['image_path'];?>">
<input type="hidden" name="size" value="<?php echo $_POST['size'];?>">
<input type="hidden" name="bedrooms" value="<?php echo $_POST['bedrooms'];?>">
<input type="hidden" name="bathrooms" value="<?php echo $_POST['bathrooms'];?>">
<input type="hidden" name="price" value="<?php echo $_POST['price'];?>">
<input type="hidden" name="sort" value="<?php echo $_POST['sort'];?>">
<input type="hidden" name="display_flag" value="<?php echo $_POST['display_flag'];?>">
