<input type="hidden" name="id" value="<?php echo $_POST['id'];?>">
<input type="hidden" name="listings_id" value="<?php echo $_POST['listings_id'];?>">
<input type="hidden" name="head" value="<?php echo $_POST['head'];?>">
<input type="hidden" name="sub_head" value="<?php echo $_POST['sub_head'];?>">
<input type="hidden" name="body" value="<?php echo $_POST['body'];?>">
<input type="hidden" name="image_path" value="<?php echo $_POST['image_path'];?>">
<input type="hidden" name="image_path_caption" value="<?php echo $_POST['image_path_caption'];?>">
<input type="hidden" name="sort" value="<?php echo $_POST['sort'];?>">
<input type="hidden" name="display_flag" value="<?php echo $_POST['display_flag'];?>">
